project:
  type: website
  output-dir: docs

website:
  title: "shiny"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Beta.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

filters: 
  - shinylive